### ISSUE TITLE
mock 数据

### ISSUE THREAD

**Issue by MrFuFuFu** [shanbay/mock-api#1]
所以，mock 数据还是要准备好对应的 json 数据是么...数据量非常复杂，场景非常多的情况下，这种 mock 数据，完全不能人为准备吧...这是只做了对应的拦截，取 mock 数据的情况是吧...这和 new 一个 `Test.java` 是一个意思咩

**Comment by MrFuFuFu** [comment]
艾玛...才发现...居然是扇贝，我又来了，赶紧开放你们的每日一句的 API 接口，最好是带配图的~！！本宝宝用扇贝600多天了...每日一句一句都没背过...

**Comment by shanbay-wyh** [comment]
有计划开放接口，我们正在重新设计这块代码，月底前应当可以开放。

**Comment by zzzhoukang** [comment]
@MrFuFuFu 

简单说下扇贝的开发模式：后端先写api文档，然后移动端和后端可以基于这份文档**并行**开发，文档包含哪些数据？
1. api url 声明；
2. api 参数声明；
3. api 返回数据实例；
   ...

所以文档里的示例数据可以作为mock数据源（文档在整个开发流程中很重要，遵循先设计后开发）。

另外，开发过程中常遇到一个问题是：如何测试某个特殊状态下的UI显示&功能逻辑？ 原先做法可能是hardcode 代码或者debug change value，这些做法都没有mock api来的简单方便。 

mock本身的局限性还是很大的，它只是解决了开发过程某一特定问题，能够在一定范围内提高开发效率；

**Comment by MrFuFuFu** [comment]
@zzzhoukang 原来如此，这就能理解，你们能拿到 mock 数据源的问题了。我们的接口文档是由移动端负责设计，在产品需求和视觉稿确定了之后，进行 API 设计。所以，并没有数据源。但服务端开发进度又总是慢于移动端，所以，在移动端自测阶段，测试数据源的问题就显得尤为重要...我们也在考虑这块的问题，应该很快会有个方案。

另外 @shanbay-wyh 很棒，我静等~~

**Comment by MrFuFuFu** [comment]
By the way. 扇贝的书...买不起了...凡尔纳的看完之后，就切 kindle 的怀抱去了....别打我...

**Comment by zzxT** [comment]
http client 是只有在使用okhttp的时候，这个库才能使用是吗？

**Comment by zzzhoukang** [comment]
@zzxT 是的，目前仅支持OkHttp（其实Android 6.0出来后，就不建议再用Apache HttpClient了）。
